# Generated by Django 4.0.7 on 2022-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_reports',
            name='problems',
            field=models.TextField(),
        ),
    ]
