# Generated by Django 4.1 on 2022-08-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_reports',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='account_id',
        ),
        migrations.AddField(
            model_name='users',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.accounts'),
        ),
        migrations.AlterField(
            model_name='daily_reports',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daily_reports',
            name='date_deleted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daily_reports',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
