# Generated by Django 4.0.7 on 2022-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_daily_reports_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
