# Generated by Django 4.0.7 on 2022-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_reports',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
