# Generated by Django 4.0.7 on 2022-08-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_users_account_id_users_account_and_more'),
        ('db', '0006_alter_accounts_email_alter_accounts_id_and_more'),
    ]

    operations = [
    ]
